Repository Pratham660/winter2020, pull requests merged in 2022-10, with the labels that each got.

#1 Scene 1 code for AR Project covid
  scene.bin
  scene.gltf
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted

#2 codes for enhancing features of BOT
  empty.wbt
  my_controller.py
Labels: enhancement, hacktoberfest-accepted

#3 added code forvideo chat feature using firebase authentication
  project_video_chat-master.zip
Labels: documentation, enhancement, hacktoberfest-accepted
